version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
