default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    if is_ci then
      install_mint
      mint_bootstrap
    end
  end

  lane :test do
    swiftlint(
      executable: mint_which(package: 'swiftlint'),
      strict: true,
      raise_if_swiftlint_error: true
    )
    swiftformat(
      executable: mint_which(package: 'swiftformat'),
      lint: true
    )
    scan
  end
end
