default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    if is_ci then
      install_mint
      mint_bootstrap
    end
  end

  lane :test do
    check_generated_code
    swiftlint(
      executable: mint_which(package: 'swiftlint'),
      strict: true,
      raise_if_swiftlint_error: true
    )
    swiftformat(
      executable: mint_which(package: 'swiftformat'),
      lint: true
    )
    scan
  end

  lane :check_generated_code do
    mint_run(command: "swiftgen")
    ensure_no_changes(
      path: "quick-scan/generated",
      show_diff: false,
      error_message: "Generated code is different than swiftgen output. Run `mint run swiftgen` to re-generate code."
    )

    ENV["SOURCERY_EXECUTABLE"] = mint_which(package: 'sourcery')
    sourcery(config: "quick-scanTests/.sourcery.yml")

    ensure_no_changes(
      path: "quick-scanTests/generated",
      show_diff: false,
      error_message: "Generated code is different than sourcery output. Run `mint run sourcery` in `quick-scanTests` directory to re-generate code."
    )
  end
end
